name: colorcheck
description: A flutter package exposing a Color class which can be used to create, convert, and compare colors.
version: 0.0.2
homepage: https://github.com/Chromicle/color_check/blob/master/lib/colorcheck.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
